// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Logout_Working', function() {
  
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Logout_Working', async function() {
    // Test name: Logout_Working
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://3.90.66.68:3000/login")
    // 2 | setWindowSize | 1440x900 | 
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    // 3 | click | css=.sign-in-form > .input-field:nth-child(3) > input | 
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).click()
    // 4 | type | css=.sign-in-form > .input-field:nth-child(3) > input | test2@gmail.com
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).sendKeys("test2@gmail.com")
    // 5 | type | css=.sign-in-form > .input-field:nth-child(4) > input | Test@123
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(4) > input")).sendKeys("Test@123")
    // 6 | click | id=sign-in-btn | 
    await driver.findElement(By.id("sign-in-btn")).click()
    // 7 | click | id=logout_button | 
    await driver.findElement(By.id("logout_button")).click()
    // 8 | click | css=.sign-in-form > .input-field:nth-child(3) > input | 
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).click()
    // 9 | type | css=.sign-in-form > .input-field:nth-child(3) > input | test2@gmail.com
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).sendKeys("test2@gmail.com")
    // 10 | click | css=.input-field:nth-child(4) > .fa-lock | 
    await driver.findElement(By.css(".input-field:nth-child(4) > .fa-lock")).click()
    // 11 | click | css=.sign-in-form > .input-field:nth-child(4) > input | 
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(4) > input")).click()
    // 12 | type | css=.sign-in-form > .input-field:nth-child(4) > input | Test@123
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(4) > input")).sendKeys("Test@123")
    // 13 | click | id=sign-in-btn | 
    await driver.findElement(By.id("sign-in-btn")).click()
    // 14 | click | id=user_history | 
    await driver.findElement(By.id("user_history")).click()
    // 15 | click | css=.btn | 
    await driver.findElement(By.css(".btn")).click()
    // 16 | click | id=summarize | 
    await driver.findElement(By.id("summarize")).click()
    // 17 | click | id=logoutButton | 
    await driver.findElement(By.id("logoutButton")).click()
    // 18 | click | css=.sign-in-form > .input-field:nth-child(3) > input | 
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).click()
    // 19 | type | css=.sign-in-form > .input-field:nth-child(3) > input | test2@gmail.com
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).sendKeys("test2@gmail.com")
    // 20 | click | css=.sign-in-form > .input-field:nth-child(4) > input | 
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(4) > input")).click()
    // 21 | type | css=.sign-in-form > .input-field:nth-child(4) > input | Test@123
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(4) > input")).sendKeys("Test@123")
    // 22 | click | id=sign-in-btn | 
    await driver.findElement(By.id("sign-in-btn")).click()
    // 23 | click | id=getUserDetails | 
    await driver.findElement(By.id("getUserDetails")).click()
    // 24 | click | id=logoutButton | 
    await driver.findElement(By.id("logoutButton")).click()
  })
})
