// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Signup_Sucsess', function() {
  
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Signup_Sucsess', async function() {
    // Test name: Signup_Sucsess
    // Step # | name | target | value
    // 1 | open | /login | 
    await driver.get("http://3.90.66.68:3000/login")
    // 2 | setWindowSize | 1440x900 | 
    await driver.manage().window().setRect({ width: 1440, height: 900 })
    // 3 | click | id=sign-up-btn1 | 
    await driver.findElement(By.id("sign-up-btn1")).click()
    // 4 | click | css=.input-field:nth-child(2) > input | 
    await driver.findElement(By.css(".input-field:nth-child(2) > input")).click()
    // 5 | type | css=.input-field:nth-child(2) > input | Test1
    await driver.findElement(By.css(".input-field:nth-child(2) > input")).sendKeys("Test1")
    // 6 | type | css=.sign-up-form > .input-field:nth-child(3) > input | Test
    await driver.findElement(By.css(".sign-up-form > .input-field:nth-child(3) > input")).sendKeys("Test")
    // 7 | type | css=.sign-up-form > .input-field:nth-child(4) > input | Test3@gmail.com
    await driver.findElement(By.css(".sign-up-form > .input-field:nth-child(4) > input")).sendKeys("Test3@gmail.com")
    // 8 | type | css=.input-field:nth-child(5) > input | Test@123
    await driver.findElement(By.css(".input-field:nth-child(5) > input")).sendKeys("Test@123")
    // 9 | click | id=sign-up-btn | 
    await driver.findElement(By.id("sign-up-btn")).click()
    // 10 | click | css=.sign-in-form | 
    await driver.findElement(By.css(".sign-in-form")).click()
    // 11 | click | css=.sign-in-form > .input-field:nth-child(3) > input | 
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).click()
    // 12 | type | css=.sign-in-form > .input-field:nth-child(3) > input | test3@gmail.com
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(3) > input")).sendKeys("test3@gmail.com")
    // 13 | type | css=.sign-in-form > .input-field:nth-child(4) > input | Test@123
    await driver.findElement(By.css(".sign-in-form > .input-field:nth-child(4) > input")).sendKeys("Test@123")
    // 14 | click | id=sign-in-btn | 
    await driver.findElement(By.id("sign-in-btn")).click()
    // 15 | click | id=logout_button | 
    await driver.findElement(By.id("logout_button")).click()
  })
})
